### ISSUE TITLE
Failed to activate the one-vibrancy package

### ISSUE THREAD

**Issue by JonnyCBB** [simurai/one-vibrancy#1]
[Enter steps to reproduce:]

1. Open settings panel
2. try to install the one-vibrancy package

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.10.5
**Thrown From**: [one-vibrancy](https://github.com/simurai/one-vibrancy) package 0.1.0

### Stack Trace

Failed to activate the one-vibrancy package

```
At require(...).remote.getCurrentWindow(...).setVibrancy is not a function

TypeError: require(...).remote.getCurrentWindow(...).setVibrancy is not a function
    at Object.setEffect (/packages/one-vibrancy/lib/one-vibrancy.js:26:55)
    at /packages/one-vibrancy/lib/one-vibrancy.js:8:12
    at Config.module.exports.Config.observeKeyPath (/Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/src/config.js:625:13)
    at Config.module.exports.Config.observe (/Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/src/config.js:150:27)
    at Object.activate (/packages/one-vibrancy/lib/one-vibrancy.js:7:17)
    at Package.module.exports.Package.activateNow (/Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (/Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Users/jbrooks-bartlett/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -1:42.1.0 settings-view:open (input.hidden-input)
     -1:19.4.0 core:confirm (input.hidden-input)
  2x -1:16.9.0 core:backspace (input.hidden-input)
     -1:04.9.0 core:confirm (input.hidden-input)
     -0:53.9.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:48.8.0 core:backspace (input.hidden-input)
     -0:46.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-clock 0.1.12 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-python-debugger 0.3.4 
atom-ternjs 0.18.3 
auto-detect-indentation 1.3.0 
autocomplete-python 1.9.1 
busy-signal 1.4.3 
fancy-bracket-matcher 1.0.1 
file-icons 2.1.8 
fonts 3.0.2 
highlight-line 0.12.0 
highlight-selected 0.13.1 
Hydrogen 1.18.0 
hyperclick 0.1.1 
indent-guide-improved 1.4.12 
indentation-indicator 1.0.0 
ink 0.7.4 
intentions 1.1.2 
javascript-snippets 1.2.1 
julia-client 0.6.0 
kite 0.30.0 
language-julia 0.11.0 
language-r 0.4.1 
latex-completions 0.3.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-flake8 2.2.1 
linter-lintr 1.1.4 
linter-ui-default 1.6.2 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
markdown-toc 0.4.2 
markdown-writer 2.6.5 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
one-vibrancy 0.1.0 
pdf-view 0.59.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
pretty-json 1.6.3 
python-indent 1.0.3 
qolor 0.4.2 
sourcefetch 0.0.0 
split-diff 1.4.3 
symbols-tree-view 0.14.0 
tabs-to-spaces 1.0.3 
tool-bar 1.1.0 
trailing-spaces 0.4.0 
uber-juno 0.1.2 
```

**Comment by simurai** [comment]
Sorry, forgot to mention that this package needs Atom version `1.19`, which is still in [Beta](https://atom.io/beta).

**Comment by JonnyCBB** [comment]
Thanks for letting me know. The package looks cool and I look forward to using it
